In [2]:
import pandas as pd
'''add, subtract, multiply, division, mod, power, reciprocal, @(matrix multiplication),transpose (converting the rows into column and vise versa)'''
'''min, max, argmin, argmax, sqrt, sin, cos, cumsum'''

'min, max, argmin, argmax, sqrt, sin, cos, cumsum'

In [16]:
ar1=np.array([1,2,3])
ar1=ar1+3
ar1

array([4, 5, 6])

In [18]:
ar1=np.array([1,2,3])
ar2=np.array([1,2,3])
var=ar1+ar2
var

array([2, 4, 6])

In [21]:
ar1=np.array([1,2,3])
ar2=np.array([1,2,3])
add=np.add(ar1,ar2)
add

array([2, 4, 6])

In [22]:
ar1=np.array([1,2,3])
ad=np.add(ar1,3)
ad

array([4, 5, 6])

In [19]:
ar1=np.array([1,2,3])
ar1=ar1-3
ar1

array([-2, -1,  0])

In [20]:
ar1=np.array([1,2,3])
ar2=np.array([1,2,3])
var=ar1-ar2
var

array([0, 0, 0])

In [25]:
ar1=np.array([1,2,3])
ar2=np.array([1,2,3])
ans=np.subtract(ar1,ar2)
ans

array([0, 0, 0])

In [26]:
ar1=np.array([1,2,3])
ar2=np.array([1,2,3])
ans=np.multiply(ar1,ar2)
ans

array([1, 4, 9])

In [27]:
ar1=np.array([1,2,3])
ar2=np.array([1,2,3])
ans=np.divide(ar1,ar2)
ans

array([1., 1., 1.])

In [28]:
ar1=np.array([1,2,3])
ar2=np.array([1,2,3])
ans=np.mod(ar1,ar2)
ans

array([0, 0, 0])

In [29]:
ar1=np.array([1,2,3])
ar2=np.array([1,2,3])
ans=np.power(ar1,ar2)
ans

array([ 1,  4, 27])

In [30]:
ar1=np.array([1,2,3])
ans=np.reciprocal(ar1)
ans

array([1, 0, 0])

In [31]:
#For Multidimentional 
ar1=np.array([[1,2,3],[1,2,3]])
ar2=np.array([[1,2,3],[1,2,3]])
var=ar1+ar2
var

array([[2, 4, 6],
       [2, 4, 6]])

In [32]:
ar1=np.array([[1,2,3],[1,2,3]])
ar2=np.array([[1,2,3],[1,2,3]])
var=ar1*ar2
var

array([[1, 4, 9],
       [1, 4, 9]])

In [8]:
ar1=np.array([[1,2,3],[1,2,3]])
ar2=np.array([[1,2,3],[1,2,3]])
var=ar1**ar2
var

array([[ 1,  4, 27],
       [ 1,  4, 27]])

In [9]:
ar1=np.array([[1,2,3],[1,2,3]])
ar2=np.array([[1,2,3],[1,2,3]])
var=ar1%ar2
var

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
ar1=np.array([[1,2,3],[1,2,3]])
ar2=np.array([[1,2,3],[1,2,3]])
var=ar1//ar2
var

array([[1, 1, 1],
       [1, 1, 1]])

In [33]:
ar1=np.array([[1,2,3],[1,2,3]])
ar2=np.array([[1,2,3],[1,2,3]])
var=np.add(ar1,ar2)
var

array([[2, 4, 6],
       [2, 4, 6]])

In [43]:
ar1=np.array([1,2,3,5,6,7,9])
print("min ",np.min(ar1)," Position is ",np.argmin(ar1) )
print("max ",np.max(ar1)," Position is ",np.argmax(ar1) )
print("sqrt  ",np.sqrt(ar1))
print("sin  ",np.sin(ar1))
print("con  ",np.cos(ar1))


len(ar1)

min  1  Position is  0
max  9  Position is  6
sqrt   [1.         1.41421356 1.73205081 2.23606798 2.44948974 2.64575131
 3.        ]
sin   [ 0.84147098  0.90929743  0.14112001 -0.95892427 -0.2794155   0.6569866
  0.41211849]
con   [ 0.54030231 -0.41614684 -0.9899925   0.28366219  0.96017029  0.75390225
 -0.91113026]


7

In [45]:
ones=np.ones(10)
cumsum=np.cumsum(ones)
print(ones)
print(cumsum)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [40]:
ar1=np.array([[1,2,3,4],[3,4,5,6]])
print("Axis=0 Column   :  min ",np.min(ar1,axis=0)," Position is ",np.argmin(ar1,axis=0) )
print("Axis=0 Column   :  max ",np.max(ar1,axis=0)," Position is ",np.argmax(ar1,axis=0) )
print("Axis=1 Row   :  min ",np.min(ar1,axis=1)," Position is ",np.argmin(ar1,axis=1) )
print("Axis=1 Row   :  max ",np.max(ar1,axis=1)," Position is ",np.argmax(ar1,axis=1) )
len(ar1)

Axis=0 Column   :  min  [1 2 3 4]  Position is  [0 0 0 0]
Axis=0 Column   :  max  [3 4 5 6]  Position is  [1 1 1 1]
Axis=1 Row   :  min  [1 3]  Position is  [0 0]
Axis=1 Row   :  max  [4 6]  Position is  [3 3]


2

In [6]:
import numpy as np
ar1=np.array([[3,7],[4,9]])
ar2=np.array([[6,2],[5,8]])
ans=ar1@ar2
print(ans)


[[53 62]
 [69 80]]


In [10]:
ar1=np.array([[3,7],[4,9]])
ar2=np.transpose(ar1)
print(ar2)

[[3 4]
 [7 9]]
