In [1]:
import numpy as np
var1=np.array([1,2,3,4])
var2=np.array([1,2,3])
print(var1+var2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [11]:
#Rules While Performing the Operation
#same dimention--compare  right side dimentio digit  (1*3) and (3*1) #both are different but we got 1 as a digit
                                                    #(2*3) and (3*1) #both are different so not possible
#If dimention is different then we should need any one of them is 1

In [5]:
var1=np.array([1,2,3])
var2=np.array([[1],[2],[3]])
print()
print(var1)
print()
print(var2)
print()
print(var1+var2)


[1 2 3]

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [6]:
var1=np.array([1,2,3])
var2=np.array([[1],[2],[3]])
print()
print(var1)
print()
print(var2)
print()
print(var1*var2)


[1 2 3]

[[1]
 [2]
 [3]]

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [7]:
var1=np.array([1,2,3])
var2=np.array([[1],[2],[3]])
print()
print(var1)
print()
print(var2)
print()
print(var1/var2)


[1 2 3]

[[1]
 [2]
 [3]]

[[1.         2.         3.        ]
 [0.5        1.         1.5       ]
 [0.33333333 0.66666667 1.        ]]


In [12]:
#multiplying 2*1 and 2*3 as we got one from right side the operation is possible and size or res=3*2
x=np.array([[1],[2]])
print(x.shape)

y=np.array([[1,2,3],[1,2,3]])
print(y.shape)

print(x+y)


(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]
