In [6]:
import numpy as np
ar=np.array([1,4,31])
co=ar.copy() #copy the data
print(co)
co[1]=1111
print(ar)

[ 1  4 31]
[ 1  4 31]


In [5]:
ar=np.array([1,4,3,1])
co=ar.view() #not copy it show the original data if you change this data i.e original data gets changed
print(co)
co[1]=1111
print(ar)

[1 4 3 1]
[   1 1111    3    1]


In [11]:
#No. of element should be same to join the array
ar1=np.array([1,4,3,1])
ar2=np.array([6,9,2,7])
arr=np.concatenate((ar1,ar2))
print(arr)


[1 4 3 1 6 9 2 7]


In [12]:
#No. of element should be same to join the array
ar1=np.array([[1,4],[3,1]])
ar2=np.array([[6,9],[2,7]])
arr=np.concatenate((ar1,ar2),axis=1)
print(arr)
print()
arr=np.concatenate((ar1,ar2),axis=0)
print(arr)

[[1 4 6 9]
 [3 1 2 7]]

[[1 4]
 [3 1]
 [6 9]
 [2 7]]


In [17]:
ar1=np.array([1,4,3,1])
ar2=np.array([6,9,2,7])
arr=np.stack((ar1,ar2),axis=1)
print(arr)
print()
arr=np.stack((ar1,ar2),axis=0)
print(arr)
print("---------")
arr=np.hstack((ar1,ar2)) #Horizontal
print(arr)
print()
arr=np.vstack((ar1,ar2)) #Vertical or Column
print(arr)
print()
arr=np.dstack((ar1,ar2)) #Height
print(arr)

[[1 6]
 [4 9]
 [3 2]
 [1 7]]

[[1 4 3 1]
 [6 9 2 7]]
---------
[1 4 3 1 6 9 2 7]

[[1 4 3 1]
 [6 9 2 7]]

[[[1 6]
  [4 9]
  [3 2]
  [1 7]]]


In [21]:
#split of an array
ar1=np.array([1,4,3,1,2,3,4,4,3])
ans1=np.array_split(ar1,3)
print(ans1)
print(type(ans1))
print(ans1[0])

[array([1, 4, 3]), array([1, 2, 3]), array([4, 4, 3])]
<class 'list'>
[1 4 3]


In [22]:
#split of an array
ar1=np.array([[1,4,3],[1,2,3],[4,4,3]])
ans1=np.array_split(ar1,3)
print(ans1)
print(type(ans1))
print(ans1[0])

[array([[1, 4, 3]]), array([[1, 2, 3]]), array([[4, 4, 3]])]
<class 'list'>
[[1 4 3]]


In [24]:
#split of an array along with axis
ar1=np.array([[1,4,3],[1,2,3],[4,4,3]])
ans1=np.array_split(ar1,3,axis=0)
print(ans1)
print()
ans1=np.array_split(ar1,3,axis=1)
print(ans1)


[array([[1, 4, 3]]), array([[1, 2, 3]]), array([[4, 4, 3]])]

[array([[1],
       [1],
       [4]]), array([[4],
       [2],
       [4]]), array([[3],
       [3],
       [3]])]
