In [1]:
import numpy as np

In [2]:
var=np.array([1,2,3,4,5])
var.dtype

dtype('int32')

In [3]:
var=np.array([1.1,2,3,4,5])
var.dtype

dtype('float64')

In [4]:
var=np.array(['1.1','2','3','4','5'])
var.dtype

dtype('<U3')

In [5]:
var=np.array(['1.1','2',3,4])
var.dtype

dtype('<U11')

In [6]:
#Convertion
var=np.array([1,2,3,4,5],dtype=np.int8)
var.dtype

dtype('int8')

In [7]:
var=np.array([1,2,3,4,5],dtype="f")
var.dtype

dtype('float32')

In [10]:
#Using funtion
var=np.array([1,2,3,4,5])
new=np.float64(var)
print(new.dtype)
print(new)

float64
[1. 2. 3. 4. 5.]


In [11]:
var=[1.2,2.3,3.4,5.5,6.8,9.9]
new=np.int32(var)
print(new.dtype)
print(new)

int32
[1 2 3 5 6 9]


In [13]:
x3=np.array([1,2,3,4,5])
new1=x3.astype(float)
print(x3)
print(new1)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
