In [1]:
#shuffle, unique resize, flatten(convert 2D array to 1D array), revel

In [2]:
import numpy as np

In [7]:
arr= np.array([1,2,3,4,5,6,7,8,2,3,4,5,6])
np.random.shuffle(arr)
print(arr)


[2 5 6 3 2 4 6 8 3 1 4 7 5]


In [15]:
arr= np.array([1,2,3,4,5,6,7,8,2,3,4,5,6])
x=np.unique(arr)
y=np.unique(arr,return_index=True)
z=np.unique(arr,return_counts=True)
zz=np.unique(arr,return_index=True, return_counts=True)
print(x)
print(y)
print(z)
print(zz)

[1 2 3 4 5 6 7 8]
(array([1, 2, 3, 4, 5, 6, 7, 8]), array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64))
(array([1, 2, 3, 4, 5, 6, 7, 8]), array([1, 2, 2, 2, 2, 2, 1, 1], dtype=int64))
(array([1, 2, 3, 4, 5, 6, 7, 8]), array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64), array([1, 2, 2, 2, 2, 2, 1, 1], dtype=int64))


In [18]:
arr= np.array([1,2,3,4,5,6,7,8,2])
var=np.resize(arr,(3,3))
print(var)

[[1 2 3]
 [4 5 6]
 [7 8 2]]


In [20]:
#flatten(convert 2D array) {C,F,A,K}
#C is default i.e. row major or C-style
#F is column-major
#A is column-major order if a is Fortrain contiguors in memory, row-major order otherwise.
#K is flatten 'a' in the order the elements occur in memory 

In [33]:
arr= np.array([1,2,3,4,5,6,7,8,2])
var=np.resize(arr,(3,3))
print(var)
print("-Default is C----")

print(var.flatten())
print("--flatten---")
print(var.flatten(order='F'))
print(('****'))
print(var.flatten(order='C'))
var
print("---revel---")
print(np.ravel(var)) #C is default
print('------')
print(np.ravel(var,order='F'))

[[1 2 3]
 [4 5 6]
 [7 8 2]]
-Default is C----
[1 2 3 4 5 6 7 8 2]
--flatten---
[1 4 7 2 5 8 3 6 2]
****
[1 2 3 4 5 6 7 8 2]
---revel---
[1 2 3 4 5 6 7 8 2]
------
[1 4 7 2 5 8 3 6 2]


In [ ]:
d