In [2]:
#Creation of Matrix
import numpy as np

In [6]:
var=np.array([[1,2,3],[1,2,3]])
print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [16]:
var1=np.matrix([[1,2],[1,2]])
var2=np.matrix([[1,2],[2,3]])
print(var1*var2)  #This is Matrix multiplication
print(var1.dot(var2))

[[5 8]
 [5 8]]
[[5 8]
 [5 8]]


In [15]:
#for multipy matrix we have to use dot() funtion

In [22]:
#Funtion in Matrix
#transpose, swapaxes, inverse, power, determinate
a=np.matrix([[1,2,3],[1,2,3]])
print(np.transpose(a))
print()
print(a.T)
print()
print(np.swapaxes(a,0,1)) #convert 0 axis to 1 


[[1 1]
 [2 2]
 [3 3]]

[[1 1]
 [2 2]
 [3 3]]

[[1 1]
 [2 2]
 [3 3]]


In [24]:
a=np.matrix([[1,2],[3,4]])
print(a)
print()
print(np.swapaxes(a,0,1))


[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [26]:
#Inverse matrix
a=np.matrix([[1,2],[3,4]])
print(a)
print()
print(np.linalg.inv(a))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [27]:
#Power of matrix
a=np.matrix([[1,2],[3,4]])
print(a)
print()
print(np.linalg.matrix_power(a,0)) #for 0 indenetity matrix, for n>0 power multiplication, n<0 inverse into power

[[1 2]
 [3 4]]

[[1 0]
 [0 1]]


In [29]:
#Power of matrix
a=np.matrix([[1,2],[3,4]])
print(a)
print()
print(np.linalg.matrix_power(a,2))##for 0 indenetity matrix, for n>0 power multiplication, n<0 inverse into power

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]


In [30]:
#Power of matrix
a=np.matrix([[1,2],[3,4]])
print(a)
print()
print(np.linalg.matrix_power(a,-2))##for 0 indenetity matrix, for n>0 power multiplication, n<0 inverse into power

[[1 2]
 [3 4]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [31]:
#determinant
a=np.matrix([[1,2],[3,4]])
print(a)
print()
print(np.linalg.det(a))

[[1 2]
 [3 4]]

-2.0000000000000004


In [36]:
#Power of matrix
a=np.matrix([[1,2,3],[3,4,1],[1,2,3]])
print(a)
print()
print(np.linalg.det(a))

[[1 2 3]
 [3 4 1]
 [1 2 3]]

0.0
