In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4,5,6,7])
x

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
type(x)

numpy.ndarray

In [5]:
print(x)

[1 2 3 4 5 6 7]


In [6]:
list=[1,2,3,3,4,6]

In [9]:
y=np.array(list)
y

array([1, 2, 3, 3, 4, 6])

In [11]:
#To get dimention of array we use ndim variable
y.ndim

1

In [20]:
ar2=np.array([[1,2,3,4],[1,2,3,5]])

In [23]:
print(ar2)
ar2.ndim

[[1 2 3 4]
 [1 2 3 5]]


2

In [25]:
ar3=np.array([[[1,2,3]]])
ar3

array([[[1, 2, 3]]])

In [26]:
ar3.ndim

3

In [29]:
#to create n dimention array
ar4=np.array([2,3,4,11],ndmin=10)

In [30]:
ar4

array([[[[[[[[[[ 2,  3,  4, 11]]]]]]]]]])

In [31]:
ar4.ndim

10

In [33]:
ar_zero=np.zeros(4)
ar_zero

array([0., 0., 0., 0.])

In [5]:
ar_zero_2d=np.zeros((3,4))
ar_zero_2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
ones_1=np.ones(10)
ones_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
ar_zero_2d=np.ones((3,4))
ar_zero_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
#Empty Array

In [43]:
ar_em=np.empty(3)  #It empty array but data from previous memory gets reflected
ar_em

array([6.95327625e-310, 6.95327625e-310, 6.95327625e-310])

In [44]:
ar_range=np.arange(4)
ar_range

array([0, 1, 2, 3])

In [46]:
dig=np.eye(3)
dig

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
dig1=np.eye(3,5)
dig1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [57]:
#special type array that having continuous gap
ar_lin=np.linspace(0,10,num=5)
ar_lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [3]:
import numpy as np
ar1=np.arange(1,10).reshape(3,3)
print(ar1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#Modification of an array

In [6]:
import numpy as np
x=np.array([1,2,3,4,5,6,7])

In [8]:
y=np.insert(x,0,123)#can append only int value to int array
print(y)

[123   1   2   3   4   5   6   7]


In [10]:
z=np.insert(x,(0,1,2),123)
print(x)
print(z)

[1 2 3 4 5 6 7]
[123   1 123   2 123   3   4   5   6   7]


In [12]:
z=np.insert(x,0,12.3)
print(x)
print(z)

[1 2 3 4 5 6 7]
[12  1  2  3  4  5  6  7]


In [21]:
arr=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 2]]
)
x=np.insert(arr,0,100,axis=0)
print(x)
print()
x=np.insert(arr,0,100,axis=1)
print(x)
print('-----')
x=np.insert(arr,0,[100,101,1],axis=1)
print(x)
print()
x=np.insert(arr,0,[100,101,1],axis=0)
print(x)

[[100 100 100]
 [  1   2   3]
 [  4   5   6]
 [  7   8   2]]

[[100   1   2   3]
 [100   4   5   6]
 [100   7   8   2]]
-----
[[100   1   2   3]
 [101   4   5   6]
 [  1   7   8   2]]

[[100 101   1]
 [  1   2   3]
 [  4   5   6]
 [  7   8   2]]


In [24]:
x=np.array([1,2,3,4,5,6,7])
y=np.append(x,11.1) #can append float value to int array
print(y)

[ 1.   2.   3.   4.   5.   6.   7.  11.1]


In [25]:
arr=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 2]]
)
v=np.append(arr,[[11,22,33]],axis=0)
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  2]
 [11 22 33]]


In [26]:
#Delete
x=np.array([1,2,3,4,5,6,7])
y=np.delete(x,0) #can have to index
print(y)

[2 3 4 5 6 7]


In [18]:
arr=np.array([0,1,2,3,4,5,6,7,8])
print(arr[0])
print(arr[len(arr)-1])
print("-----")
print(arr[-1])
print(arr[-9])
print("Slicing")
print(arr[1:3])
print(arr[1:6:2])
print(arr[1:])
print(arr[-1:-3:-1])
print(arr[::2])
print(arr[::-1])


0
8
-----
8
0
Slicing
[1 2]
[1 3 5]
[1 2 3 4 5 6 7 8]
[8 7]
[0 2 4 6 8]
[8 7 6 5 4 3 2 1 0]


In [4]:
import numpy as np
ar1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(ar1[0])
print(ar1[0,0])
print(ar1[1,1])
print(ar1[0,:])
print(ar1[:,0])

print("---slicing----")
print('------1')
print(ar1[1,])
print('------2')
print(ar1[:,1])
print('------3')
print(ar1[1:3,1:3])
print('------4')
print(ar1[1:3,])
print('------5')
print(ar1[:,1:3])
print('------6')
print(ar1[1:3,1])
print('------7')
print(ar1[1:3,:1])


[1 2 3]
1
5
[1 2 3]
[ 1  4  7 10]
---slicing----
------1
[4 5 6]
------2
[ 2  5  8 11]
------3
[[5 6]
 [8 9]]
------4
[[4 5 6]
 [7 8 9]]
------5
[[ 2  3]
 [ 5  6]
 [ 8  9]
 [11 12]]
------6
[5 8]
------7
[[4]
 [7]]
