In [ ]:
#rand()   0 to 1
#randn() +- close to zero
#randf() 0 to 1  (0 included and 1 excluded) [0,1)
#randint(min,max,totalnum) random number between the range [min,max)

In [1]:
import numpy as np

In [5]:
var=np.random.rand(5)
var

array([0.85464174, 0.57796338, 0.46522039, 0.51854099, 0.96199014])

In [7]:
var1=np.random.rand(3,5)
var1

array([[0.21195551, 0.72043026, 0.11098626, 0.37868836, 0.90241691],
       [0.95676619, 0.2162318 , 0.39551362, 0.30067811, 0.29789573],
       [0.93232257, 0.22287651, 0.72664704, 0.44991646, 0.19655856]])

In [8]:
var2=np.random.randn(10)
var2

array([-0.1220499 , -1.70195975,  0.22327958,  0.22013032,  0.66234155,
       -0.24174096, -0.33659302, -0.66461504,  0.44096589,  1.32367876])

In [9]:
var3=np.random.ranf(10)
var3

array([0.70123871, 0.92065196, 0.21527991, 0.95945866, 0.09959612,
       0.54322243, 0.43249894, 0.99800192, 0.9037398 , 0.18794042])

In [16]:
var4=np.random.randint(5,7,10) 
var4

array([6, 6, 6, 5, 5, 5, 5, 6, 5, 5])