In [9]:
import numpy as np
ar1=np.array([1,4,3,11,2,3,4,0,3])

In [12]:
#index
x=np.where(ar1==1)
print(x)
print()
x=np.where(ar1==4)
print(x)

x=np.where(ar1/2==0)
print(x)

x=np.where(ar1%2==0)
print(x,"Modules")

(array([0], dtype=int64),)

(array([1, 6], dtype=int64),)
(array([7], dtype=int64),)
(array([1, 4, 6, 7], dtype=int64),) Modules


In [24]:
#For Searching in Sorted Array
import numpy as np
ar1=np.array([0,1,2,3,4,5,6,7,8,9,10])
x=np.searchsorted(ar1,55) #In which index we can insert the specified element
print(x)
x=np.searchsorted(ar1,-55) #In which index we can insert the specified element
print(x)
print("we can pass multiple element to search its lection where we can place the element")
x=np.searchsorted(ar1,[55,11,0]) #In which index we can insert the specified element
print(x)
print("Above one are searching from left to right")
print("To search from right to left we have to pass side arg as right")
x=np.searchsorted(ar1,55,side='right') #In which index we can insert the specified element
print(x)
x=np.searchsorted(ar1,-55,side='right') #In which index we can insert the specified element
print(x)

11
0
we can pass multiple element to search its lection where we can place the element
[11 11  0]
Above one are searching from left to right
To search from right to left we have to pass side arg as right
11
0


In [26]:
#To sort an array
ar1=np.array([1,4,3,11,2,3,4,0,3])
print(np.sort(ar1))
ar1=np.array(['a','A','b','B'])
print(np.sort(ar1))

[ 0  1  2  3  3  3  4  4 11]
['A' 'B' 'a' 'b']


In [27]:
ar1=np.array([[1,4,3],[1,2,3],[4,4,3]])
print(np.sort(ar1))

[[1 3 4]
 [1 2 3]
 [3 4 4]]


In [28]:
#Filtering of an array


In [30]:
ar1=np.array([1,4,3,11])
f=[True,True,False,False]
new_ar1=ar1[f]
print(new_ar1)
print(type(new_ar1))

[1 4]
<class 'numpy.ndarray'>
