In [1]:
#To find the shape and reshaping and different variable
"""
ndim
shape
size
itemsize
dtype
ndmin while creating the array
"""

In [2]:
import numpy as np

In [8]:
var= np.array([[1,2,3,4],[1,2,4,5]])
print(var)
print()
print(var.shape)
print()

[[1 2 3 4]
 [1 2 4 5]]

(2, 4)



In [36]:
var1=np.array([1,2,3,4], ndmin=4, dtype=np.int64)#To set the dimention
print(var1)
print(var1.ndim)  # to get the dimention
print(var1.shape,"shape")
print(var1.size,"element")
print(var1.dtype,"dtype")
print(var1.itemsize,"itemsize in type")

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4) shape
4 element
int64 dtype
8 itemsize in type


In [30]:
#reshaping of an array
var2=np.array([1,2,3,4,5,6,7,8,9])
print(var2)
print(var2.ndim)
print('Converting 1D to 2D')
x=var2.reshape(3,3) #first no. is row and 2nd is column
print(x)
print(x.ndim)
print(x.shape)


[1 2 3 4 5 6 7 8 9]
1
Converting 1D to 2D
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [28]:
var2=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var2)
print(var2.ndim)
print('Converting 1D to 3D')
x=var2.reshape(2,3,2)
print(x)
print(x.ndim)

print('Converting 3D array to 1D array')
ab=x.reshape(-1)
print(ab)
print(ab.ndim)
print(ab.shape)



[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
Converting 1D to 3D
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
Converting 3D array to 1D array
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)
