In [1]:
import numpy as np
'''
sort() will return sorted copy
argsort() return the indices that would sort an array
array_name.sort() use array name and sort it in place
'''

'\nsort() will return sorted copy\nargsort() return the indices that would sort an array\narray_name.sort() use array name and sort it in place\n'

In [10]:
ar=np.array([15,25,53,45,31,21,10,12,334,55,677])
arr=np.sort(ar)
print(arr)
arr2=np.sort(ar)[::-1]
print(arr2)

[ 10  12  15  21  25  31  45  53  55 334 677]
[677 334  55  53  45  31  25  21  15  12  10]


In [12]:
ar=np.array([1,2,3,0])
arr=np.argsort(ar)
print(arr)

[3 0 1 2]


In [20]:
ar=np.array([1,2,3,0])
ar.sort()
print(ar)

[0 1 2 3]


In [24]:
x=np.array([[12,11,15],[21,25,20],[18,27,16]])
y=np.sort(x) #default asix=1
print(y)

[[11 12 15]
 [20 21 25]
 [16 18 27]]


In [25]:
x=np.array([[12,11,15],[21,25,20],[18,27,16]])
y=np.sort(x,axis=0) # asix=0 for Column
print(y)

[[12 11 15]
 [18 25 16]
 [21 27 20]]


In [26]:
x=np.array([[12,11,15],[21,25,20],[18,27,16]])
y=np.argsort(x) #default asix=1
print(y)

[[1 0 2]
 [2 0 1]
 [2 0 1]]


In [27]:
x=np.array([[12,11,15],[21,25,20],[18,27,16]])
y=np.argsort(x,axis=0) #default asix=1
print(y)

[[0 0 0]
 [2 1 2]
 [1 2 1]]


In [30]:
x=np.array([[12,11,15],[21,25,20],[18,27,16]])
x.sort()
print(x)
print('------------')
x=np.array([[12,11,15],[21,25,20],[18,27,16]])
x.sort(axis=0)
print(x)

[[11 12 15]
 [20 21 25]
 [16 18 27]]
------------
[[12 11 15]
 [18 25 16]
 [21 27 20]]
